name: Deployment
on:
  push:
    branches:
      - master
      - staging
jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r framework/requirements.txt
          pip install -r api/packages.txt

      - name: Install frontend dependencies
        working-directory: frontend
        run: |
          yarn install

      - name: Run deployment
        run: |
          echo "${{ secrets.secrets }}" > secrets.env
          ./lambctl deploy -y